name: qaqcdev
channels:
- conda-forge
dependencies:
- python=3.8
- xarray
- zarr
- scipy
- matplotlib
- fsspec
- cmocean
- s3fs
# Frontend stuff
- yarn
- nodejs
- pip
- pip:
  - git+https://github.com/OOI-CabledArray/rca-data-tools.git@main