name: BB Hydrophones (Docker Image)
on:
  schedule:
  - cron: "0 11 * * *" #every day at 12:00 UTC (4:00 AM PST)
  workflow_dispatch:

jobs:
  run-acoustic-pipeline:
    name: ${{matrix.name}} spectrograms
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - refdes: 'RS01SLBS-LJ01A-09-HYDBBA102'
            name: 'RS01SLBS-LJ01A-09-HYDBBA102'
          - refdes: 'CE04OSBP-LJ01C-11-HYDBBA105'
            name: 'CE04OSBP-LJ01C-11-HYDBBA105'
          - refdes: "CE02SHBP-LJ01D-11-HYDBBA106"
            name: 'CE02SHBP-LJ01D-11-HYDBBA106'
          - refdes: "RS03AXBS-LJ03A-09-HYDBBA302"
            name: 'RS03AXBS-LJ03A-09-HYDBBA302'
          - refdes: "RS03AXPS-PC03A-08-HYDBBA303"
            name: 'RS03AXPS-PC03A-08-HYDBBA303'
          - refdes: "RS01SBPS-PC01A-08-HYDBBA103"
            name: 'RS01SBPS-PC01A-08-HYDBBA103'
    defaults:
      run:
        shell: bash -l {0}
    container:
      image: jdduprey/ooi-hyd-tools:latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.GH_PAT }}
      - name: Run acoustic pipeline mseed -> spectrograms
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
          TASK_ROLE_ARN: ${{ secrets.TASK_ROLE_ARN }}
          EXECUTION_ROLE_ARN: ${{ secrets.EXECUTION_ROLE_ARN }}
          PREFECT_WORKSPACE: jdupreyuwedu/ooi-rca-prefect2
          PREFECT_KEY: ${{ secrets.PREFECT_KEY }}
          AWS_KEY: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          # Authenticate with prefect2 cloud 
          prefect cloud login --key "${{ env.PREFECT_KEY }}" --workspace "${{ env.PREFECT_WORKSPACE }}"
          # Run full acoustic pipeline mseed -> spectrograms
          acoustic-pipeline --hyd-refdes ${{matrix.refdes}} --fudge-factor 0.021 --apply-cals true --s3-sync true --flag all --parallel-in-cloud true
