name: Update QAQC HITL Notes

on:
  schedule:
  - cron: "0 0 * * *" 
  workflow_dispatch:

env:
  PYTHON_VERSION: 3.8

jobs:
  qaqc-notes:
    name: Run QAQC HITL Notes
    runs-on: ubuntu-20.04
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.GH_PAT }}
      - name: Setup python
        uses: actions/setup-python@v1
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Setup miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-activate-base: false
          activate-environment: rca-data-env
          channel-priority: strict
          environment-file: .ci/environment.yaml
          use-only-tar-bz2: true
      - name: Print conda env
        run: |
          conda info
          conda list
      - name: Install package
        run: pip install git+https://github.com/OOI-CabledArray/rca-data-tools.git@main
      - name: Notes update
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET }}
        run: |
          generate_hitl_tables --s3-sync --service-json-path ${{ secrets.SERVICE_JSON_PATH }}
