name: QAQC Plots (Weekly)
# On monday run all spans including 365.
on:
  schedule:
  - cron: "0 13 * * 1" 
  workflow_dispatch:

env:
  PYTHON_VERSION: 3.11
  THRESHOLD: 5000000

jobs:
  run-pipeline:
    name: ${{ matrix.name }} Plots
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        include:
          - span: '1'
            name: 'Daily'
          - span: '7'
            name: 'Weekly'
          - span: '30'
            name: 'Monthly'
          - span: '365'
            name: 'Yearly'
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.GH_PAT }}
      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Setup miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-activate-base: false
          activate-environment: rca-data-env
          channel-priority: strict
          environment-file: .ci/environment.yaml
          use-only-tar-bz2: true
      - name: Print conda env
        run: |
          conda info
          conda list
      - name: Install package
        run: pip install git+https://github.com/OOI-CabledArray/rca-data-tools.git@main
      - name: Run pipeline plot creation
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
          TASK_ROLE_ARN: ${{ secrets.TASK_ROLE_ARN }}
          EXECUTION_ROLE_ARN: ${{ secrets.EXECUTION_ROLE_ARN }}
          PREFECT_WORKSPACE: jdupreyuwedu/ooi-rca-prefect2
          PREFECT_KEY: ${{ secrets.PREFECT_KEY }}
          AWS_KEY: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          # Authenticate with prefect2 cloud 
          prefect cloud login --key "${{ env.PREFECT_KEY }}" --workspace "${{ env.PREFECT_WORKSPACE }}"
          # Run flow
          qaqc_pipeline --all --cloud --s3-sync --span ${{ matrix.span }} --run --threshold ${{ env.THRESHOLD }}
