name: QAQC Plots Deployment Span

on:
  workflow_dispatch:

env:
  PYTHON_VERSION: 3.8
  THRESHOLD: 5000000

jobs:
  run-pipeline:
    name: ${{ matrix.name }} Plots
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        include:
          - span: '0'
            name: 'Deployments'
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.GH_PAT }}
      - name: Setup python
        uses: actions/setup-python@v1
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Setup miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-activate-base: false
          activate-environment: rca-data-env
          channel-priority: strict
          environment-file: .ci/environment.yaml
          use-only-tar-bz2: true
      - name: Print conda env
        run: |
          conda info
          conda list
      - name: Install package
        run: pip install git+https://github.com/OOI-CabledArray/rca-data-tools.git@main
      - name: Run pipeline plot creation
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
          TASK_ROLE_ARN: ${{ secrets.TASK_ROLE_ARN }}
          EXECUTION_ROLE_ARN: ${{ secrets.EXECUTION_ROLE_ARN }}
        run: |
          # Make prefect dir
          mkdir ~/.prefect

          # Login
          ###prefect auth login --key ${{ secrets.PREFECT_TOKEN }}

          # Set backend of prefect to server
          prefect backend server
          echo "[server]" >> ~/.prefect/backend.toml
          echo "endpoint = 'http://54.213.226.252:4200'" >> ~/.prefect/backend.toml

          # Run flow
          qaqc_pipeline --all --cloud --s3-sync --span ${{ matrix.span }} --run --threshold ${{ env.THRESHOLD }} --s3-bucket ${{ secrets.DASHBOARD_BUCKET }}
