name: Index Profiles (Daily)
# generate new profile indices and push to the remote indices repo
on:
  schedule:
  - cron: "30 10 * * *" 
  workflow_dispatch:

env:
  PYTHON_VERSION: 3.11

jobs:
  generate-profile-indices:
    name: Generate profile indices
    runs-on: ubuntu-latest
    steps:
       - name: Check out repo
         uses: actions/checkout@v4
         with:
          repository: jdduprey/profileIndices
          token: ${{ secrets.GH_PAT_JD }}
       - name: Setup python
         uses: actions/setup-python@v5
         with:
           python-version: ${{ env.PYTHON_VERSION }}
       - name: Install package
         run: pip install git+https://github.com/jdduprey/profileIndices.git@main
       - name: Generate profile indices
         run: |
           index-profiles --profiler 'RS03AXPS' --dataSource 'zarr' --fileCreation 'append'
           index-profiles --profiler 'RS01SBPS' --dataSource 'zarr' --fileCreation 'append'
           index-profiles --profiler 'CE04OSPS' --dataSource 'zarr' --fileCreation 'append'
       - name: Configure git
         run: |
           git config user.name "github-actions[bot]"
           git config user.email "github-actions[bot]@users.noreply.github.com"
       - name: Commit and push updates to index CSVs
         run: |
           git add -A
           git commit -m "daily profiler indices update" || echo "no changes"
           git push
       

       